name: Job Notes Saver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Prepare extension files
        run: |
          # Create extension directory and copy built files
          mkdir extension
          cp -r build/* extension/

      - name: Zip extension folder
        run: |
          cd extension
          zip -r ../extension.zip . -x '*.map' '*.txt' 'robots.txt'

      - name: Upload to Chrome Web Store
        uses: PlasmoHQ/chrome-upload-action@v1
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_path: extension.zip
          publish: false